REFACTOR DE PLANEACION_CONSTRUCCION_MF
udistrital/planeacion_construccion_mf pull request #3
Opened 2024-05-15 18:03 UTC by Mechaz123

- Se realiza el refactor de planeacion_construccion_mf, con las funcionalidades migradas.
- Se realiza también el ajuste de los estilos aplicando los colores asociados a planeacion.
- Se realiza el cambio de Endpoints a los micro mid's.

2024-05-16 19:32 UTC, milo19980525 reviewed
Por favor revisar e incluir: Readme.md, Drone.YML (poner failure.ignore al step de telegram), y en todos los archivos de variables de entorno solo pueden ir aquellas relacionadas con autenticación excepto enviroment.developenemnt.ts (este si lleva las variables de las APIs por intranet)

2024-05-16 19:32 UTC, milo19980525 requested changes
Realizar los ajustes requeridos por favor.

2024-05-17 07:12 UTC, Mechaz123 commented
Se envió un commit con los archivos faltantes, y los demás elementos relacionados al issue: https://github.com/udistrital/planeacion_cliente/issues/1050

2024-05-18 23:28 UTC, milo19980525 approved these changes

2024-05-18 23:28 UTC, merged